//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustynaKozbaLab8.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JustynaKozbaData
    {
        public short Id { get; set; }
        public string ElementName { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<int> ElementValue { get; set; }
    }
}
